/-
Copyright (c) 2026 Anthropic, PBC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/

import RH.Zeta85.Discharge.IsometricKernel

/-!
# Flat orthogonal mixing

A flat real isometry spreads every compressed coordinate across all physical
columns.  Its projection has constant diagonal.  Consequently the mixed
pair kernel splits into a correctly normalized aggregate-channel main term
and one already-summed remainder.
-/

open Filter Matrix Finset
open scoped BigOperators ComplexConjugate ComplexOrder Topology

noncomputable section

namespace RH
namespace Zeta85
namespace BalancedMixer

open Zeta23 RHLinalg

/-- A real isometric mixer with constant squared weight in every physical
coordinate. -/
structure FlatData
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    (F : QuarticGramFamily Z σ μ p v) where
  toRealData : IsometricKernel.RealData F
  flat_weight :
    ∀ (T : ℝ) (i : Fin (F.dim T))
      (a : Fin (F.blockDim T)),
      star (toRealData.toData.compression T i a) *
          toRealData.toData.compression T i a =
        (((F.dim T : ℝ)⁻¹ : ℝ) : ℂ)

/-- Every diagonal entry of the full-space mixing projection is exactly the
block-to-full dimension ratio. -/
theorem projection_diag
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : FlatData F) (T : ℝ) (i : Fin (F.dim T)) :
    IsometricKernel.projection C.toRealData T i i =
      (((F.blockDim T : ℝ) / (F.dim T : ℝ) : ℝ) : ℂ) := by
  unfold IsometricKernel.projection
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply]
  simp_rw [C.flat_weight T i]
  simp [div_eq_mul_inv]

/-- Isometry alone fixes the trace of the mixing projection. -/
theorem projection_rtrace
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : IsometricKernel.RealData F) (T : ℝ) :
    rtrace (IsometricKernel.projection C T) =
      (F.blockDim T : ℝ) := by
  unfold IsometricKernel.projection rtrace
  rw [trace_mul_cycle, C.toData.isometry T]
  simp [Matrix.trace]

/-- The diagonal main term after flat mixing: the full aggregate physical
pair kernel, scaled by the exact projection density. -/
def aggregatePairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : FlatData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    (((F.blockDim T : ℝ) / (F.dim T : ℝ) : ℝ) : ℂ) *
    ∑ i : Fin (F.dim T),
      F.atom T i ρ * F.atom T i ρ'

/-- All off-diagonal projection interactions, after the complete column
sum has already been taken. -/
def pairRemainder
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : FlatData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  IsometricKernel.projectedPairKernel C.toRealData T ρ ρ' -
    aggregatePairKernel C T ρ ρ'

/-- Exact main-plus-remainder split for the actual mixed pair kernel. -/
theorem mixedPairKernel_eq_aggregate_add_remainder
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : FlatData F) (T : ℝ) (ρ ρ' : ℂ) :
    IsometricKernel.mixedPairKernel C.toRealData T ρ ρ' =
      aggregatePairKernel C T ρ ρ' +
        pairRemainder C T ρ ρ' := by
  rw [IsometricKernel.mixedPairKernel_eq_projectedPairKernel]
  unfold pairRemainder
  ring

/-- The terminal quartic numerator generated by the aggregate-channel main
kernel. -/
def aggregateQuarticNumerator
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : FlatData F) (T : ℝ) : ℝ :=
  QuarticTransfer.pairKernelQuarticNumerator q F T
    (aggregatePairKernel C T)

/-- Measure the error only after all four cycle degrees and the terminal
linear combination have been formed. -/
def quarticRemainder
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : FlatData F) (T : ℝ) : ℝ :=
  IsometricKernel.mixedPairKernelQuarticNumerator
      q C.toRealData T -
    aggregateQuarticNumerator q C T

theorem mixedQuartic_eq_aggregate_add_remainder
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : FlatData F) (T : ℝ) :
    IsometricKernel.mixedPairKernelQuarticNumerator
        q C.toRealData T =
      aggregateQuarticNumerator q C T +
        quarticRemainder q C T := by
  unfold quarticRemainder
  ring

/-- One-sided terminal bound for the aggregate-channel main term. -/
structure AggregateQuarticLowerBound
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic) (C : FlatData F) : Prop where
  block_dimension_pos :
    ∀ᶠ T in Filter.atTop, 0 < F.blockDim T
  eventually_gt :
    ∀ x : ℝ,
      x < μ * QuarticTransfer.limitQuarticScore q μ p →
      ∀ᶠ T in Filter.atTop,
        x < aggregateQuarticNumerator q C T /
          (Z.N T (2 * T) : ℝ)

/-- The complete sum-first off-diagonal error vanishes at the dyadic zero
scale. -/
def NormalizedQuarticRemainderVanishes
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic) (C : FlatData F) : Prop :=
  Tendsto
    (fun T => quarticRemainder q C T /
      (Z.N T (2 * T) : ℝ))
    Filter.atTop (nhds 0)

/-- A strict aggregate lower bound survives any vanishing sum-first
off-diagonal error. -/
theorem AggregateQuarticLowerBound.toMixed
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    {q : TrimmedMoment.Quartic} {C : FlatData F}
    (hmain : AggregateQuarticLowerBound q C)
    (herr : NormalizedQuarticRemainderVanishes q C) :
    IsometricKernel.MixedPairKernelQuarticLowerBound
      q C.toRealData := by
  refine ⟨hmain.block_dimension_pos, ?_⟩
  intro x hx
  let δ : ℝ :=
    (μ * QuarticTransfer.limitQuarticScore q μ p - x) / 3
  have hδ : 0 < δ := by
    dsimp only [δ]
    linarith
  have hmainT : ∀ᶠ T in Filter.atTop,
      μ * QuarticTransfer.limitQuarticScore q μ p - δ <
        aggregateQuarticNumerator q C T /
          (Z.N T (2 * T) : ℝ) :=
    hmain.eventually_gt _ (by linarith)
  have herrT : ∀ᶠ T in Filter.atTop,
      -δ < quarticRemainder q C T /
        (Z.N T (2 * T) : ℝ) :=
    herr.eventually (Ioi_mem_nhds (by linarith))
  filter_upwards [hmainT, herrT] with T hm he
  rw [mixedQuartic_eq_aggregate_add_remainder]
  have hsplit :
      (aggregateQuarticNumerator q C T +
          quarticRemainder q C T) /
          (Z.N T (2 * T) : ℝ) =
        aggregateQuarticNumerator q C T /
            (Z.N T (2 * T) : ℝ) +
          quarticRemainder q C T /
            (Z.N T (2 * T) : ℝ) := by
    ring
  rw [hsplit]
  dsimp only [δ] at hm he
  linarith

end BalancedMixer
end Zeta85
end RH

end
