/-
Copyright (c) 2026 Anthropic, PBC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/

import RH.Zeta85.Discharge.IsometricBlock

/-!
# Mix columns before zero contraction

A real isometric compression can be applied to the physical columns before
the zero sums are multiplied.  The resulting scalar pair kernel contains the
orthogonal projection onto the mixed subspace, so cross-channel cancellation
happens inside each pair contraction rather than being demanded separately
from every physical channel.
-/

open Filter Matrix Finset
open scoped BigOperators ComplexConjugate ComplexOrder

noncomputable section

namespace RH
namespace Zeta85
namespace IsometricKernel

open Zeta23 RHLinalg

/-- An isometric compression whose coefficients are fixed by complex
conjugation.  Thus it is a real orthogonal mixer represented over the
complex scalars. -/
structure RealData
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    (F : QuarticGramFamily Z σ μ p v) where
  toData : IsometricBlock.Data F
  real_entries :
    ∀ (T : ℝ) (i : Fin (F.dim T))
      (a : Fin (F.blockDim T)),
      star (toData.compression T i a) =
        toData.compression T i a

/-- Mix all physical columns first, producing one transformed atom per
compressed coordinate. -/
def mixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) : ℂ :=
  ∑ i : Fin (F.dim T),
    C.toData.compression T i a * F.atom T i ρ

/-- The atom produced by the conjugate-transpose side of the compression. -/
def leftMixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) : ℂ :=
  ∑ i : Fin (F.dim T),
    star (C.toData.compression T i a) * F.atom T i ρ

/-- Real mixing makes the two transformed atoms literally identical. -/
theorem leftMixedAtom_eq_mixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) :
    leftMixedAtom C T a ρ = mixedAtom C T a ρ := by
  unfold leftMixedAtom mixedAtom
  apply Finset.sum_congr rfl
  intro i _
  rw [C.real_entries T i a]

/-- Projection in the full physical column space generated by the mixed
block. -/
def projection
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    Matrix (Fin (F.dim T)) (Fin (F.dim T)) ℂ :=
  C.toData.compression T *
    (C.toData.compression T)ᴴ

/-- The mixing matrix determines an exact idempotent projection. -/
theorem projection_sq
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    projection C T ^ 2 = projection C T := by
  unfold projection
  calc
    (C.toData.compression T *
          (C.toData.compression T)ᴴ) ^ 2 =
        C.toData.compression T *
          ((C.toData.compression T)ᴴ *
            C.toData.compression T) *
          (C.toData.compression T)ᴴ := by
      noncomm_ring
    _ = C.toData.compression T * 1 *
          (C.toData.compression T)ᴴ := by
      rw [C.toData.isometry T]
    _ = C.toData.compression T *
          (C.toData.compression T)ᴴ := by
      simp

/-- The normalized pair contraction after mixing columns first. -/
def mixedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    ∑ a : Fin (F.blockDim T),
      mixedAtom C T a ρ * mixedAtom C T a ρ'

/-- The mixed pair kernel retains the symmetry required by the existing
zero-cycle factorization. -/
theorem mixedPairKernel_comm
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) :
    mixedPairKernel C T ρ ρ' =
      mixedPairKernel C T ρ' ρ := by
  unfold mixedPairKernel
  congr 1
  apply Finset.sum_congr rfl
  intro a _
  ring

/-- The same contraction with the mixer exposed as its full-space
projection.  This is the coordinate used for Poisson and support-gap
analysis: all channel interactions have already been summed. -/
def projectedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
      F.atom T i ρ * projection C T i j *
        F.atom T j ρ'


/-- Mixing first and inserting the corresponding full-space projection are
exactly the same pair contraction. -/
theorem mixedPairKernel_eq_projectedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) :
    mixedPairKernel C T ρ ρ' =
      projectedPairKernel C T ρ ρ' := by
  unfold mixedPairKernel projectedPairKernel mixedAtom projection
  congr 1
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply]
  calc
    (∑ a : Fin (F.blockDim T),
        (∑ i : Fin (F.dim T),
            C.toData.compression T i a * F.atom T i ρ) *
          ∑ j : Fin (F.dim T),
            C.toData.compression T j a * F.atom T j ρ') =
      ∑ a : Fin (F.blockDim T),
        ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro a _
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro j _
      ring
    _ = ∑ i : Fin (F.dim T),
        ∑ a : Fin (F.blockDim T), ∑ j : Fin (F.dim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      rw [Finset.sum_comm]
    _ = ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
        ∑ a : Fin (F.blockDim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.sum_comm]
    _ = ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
        F.atom T i ρ *
          (∑ a : Fin (F.blockDim T),
            C.toData.compression T i a *
              star (C.toData.compression T j a)) *
          F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro i _
      apply Finset.sum_congr rfl
      intro j _
      rw [Finset.mul_sum, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro a _
      rw [C.real_entries T j a]
      ring

end IsometricKernel
end Zeta85
end RH

end
