/-
Copyright (c) 2026 Anthropic, PBC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
SPDX-License-Identifier: Apache-2.0
-/

import RH.Zeta85.Discharge.IsometricBlock

/-!
# Mix columns before zero contraction

A real isometric compression can be applied to the physical columns before
the zero sums are multiplied.  The resulting scalar pair kernel contains the
orthogonal projection onto the mixed subspace, so cross-channel cancellation
happens inside each pair contraction rather than being demanded separately
from every physical channel.
-/

open Filter Matrix Finset
open scoped BigOperators ComplexConjugate ComplexOrder

noncomputable section

namespace RH
namespace Zeta85
namespace IsometricKernel

open Zeta23 RHLinalg

/-- An isometric compression whose coefficients are fixed by complex
conjugation.  Thus it is a real orthogonal mixer represented over the
complex scalars. -/
structure RealData
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    (F : QuarticGramFamily Z σ μ p v) where
  toData : IsometricBlock.Data F
  real_entries :
    ∀ (T : ℝ) (i : Fin (F.dim T))
      (a : Fin (F.blockDim T)),
      star (toData.compression T i a) =
        toData.compression T i a

/-- Mix all physical columns first, producing one transformed atom per
compressed coordinate. -/
def mixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) : ℂ :=
  ∑ i : Fin (F.dim T),
    C.toData.compression T i a * F.atom T i ρ

/-- The atom produced by the conjugate-transpose side of the compression. -/
def leftMixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) : ℂ :=
  ∑ i : Fin (F.dim T),
    star (C.toData.compression T i a) * F.atom T i ρ

/-- Real mixing makes the two transformed atoms literally identical. -/
theorem leftMixedAtom_eq_mixedAtom
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a : Fin (F.blockDim T)) (ρ : ℂ) :
    leftMixedAtom C T a ρ = mixedAtom C T a ρ := by
  unfold leftMixedAtom mixedAtom
  apply Finset.sum_congr rfl
  intro i _
  rw [C.real_entries T i a]

/-- Projection in the full physical column space generated by the mixed
block. -/
def projection
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    Matrix (Fin (F.dim T)) (Fin (F.dim T)) ℂ :=
  C.toData.compression T *
    (C.toData.compression T)ᴴ

/-- The mixing matrix determines an exact idempotent projection. -/
theorem projection_sq
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    projection C T ^ 2 = projection C T := by
  unfold projection
  calc
    (C.toData.compression T *
          (C.toData.compression T)ᴴ) ^ 2 =
        C.toData.compression T *
          ((C.toData.compression T)ᴴ *
            C.toData.compression T) *
          (C.toData.compression T)ᴴ := by
      noncomm_ring
    _ = C.toData.compression T * 1 *
          (C.toData.compression T)ᴴ := by
      rw [C.toData.isometry T]
    _ = C.toData.compression T *
          (C.toData.compression T)ᴴ := by
      simp

/-- The normalized pair contraction after mixing columns first. -/
def mixedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    ∑ a : Fin (F.blockDim T),
      mixedAtom C T a ρ * mixedAtom C T a ρ'

/-- The mixed pair kernel retains the symmetry required by the existing
zero-cycle factorization. -/
theorem mixedPairKernel_comm
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) :
    mixedPairKernel C T ρ ρ' =
      mixedPairKernel C T ρ' ρ := by
  unfold mixedPairKernel
  congr 1
  apply Finset.sum_congr rfl
  intro a _
  ring

/-- The same contraction with the mixer exposed as its full-space
projection.  This is the coordinate used for Poisson and support-gap
analysis: all channel interactions have already been summed. -/
def projectedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
      F.atom T i ρ * projection C T i j *
        F.atom T j ρ'


/-- Mixing first and inserting the corresponding full-space projection are
exactly the same pair contraction. -/
theorem mixedPairKernel_eq_projectedPairKernel
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) (ρ ρ' : ℂ) :
    mixedPairKernel C T ρ ρ' =
      projectedPairKernel C T ρ ρ' := by
  unfold mixedPairKernel projectedPairKernel mixedAtom projection
  congr 1
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply]
  calc
    (∑ a : Fin (F.blockDim T),
        (∑ i : Fin (F.dim T),
            C.toData.compression T i a * F.atom T i ρ) *
          ∑ j : Fin (F.dim T),
            C.toData.compression T j a * F.atom T j ρ') =
      ∑ a : Fin (F.blockDim T),
        ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro a _
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro j _
      ring
    _ = ∑ i : Fin (F.dim T),
        ∑ a : Fin (F.blockDim T), ∑ j : Fin (F.dim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      rw [Finset.sum_comm]
    _ = ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
        ∑ a : Fin (F.blockDim T),
          C.toData.compression T i a *
            C.toData.compression T j a *
            F.atom T i ρ * F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro i _
      rw [Finset.sum_comm]
    _ = ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
        F.atom T i ρ *
          (∑ a : Fin (F.blockDim T),
            C.toData.compression T i a *
              star (C.toData.compression T j a)) *
          F.atom T j ρ' := by
      apply Finset.sum_congr rfl
      intro i _
      apply Finset.sum_congr rfl
      intro j _
      rw [Finset.mul_sum, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro a _
      rw [C.real_entries T j a]
      ring


/-- Every entry of the enlarged-window matrix as its canonical finite zero
sum, before any compression is taken. -/
theorem A_apply_eq_zeroSum
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (T : ℝ) (i j : Fin (F.dim T)) :
    F.A T i j =
      ((F.hatDenominator T)⁻¹ : ℂ) *
        ∑ ρ ∈ ZeroSide.ZI Z T,
          (Z.mult ρ : ℂ) * F.atom T i ρ *
            F.atom T j ρ := by
  unfold QuarticGramFamily.A QuarticGramFamily.rawTruncatedGram
  rw [finsum_mem_eq_finite_toFinset_sum _
    (ZeroSide.ZIprime_finite Z T)]
  rfl

/-- The compressed entry with the matrix products and finite zero sum fully
opened, but before the sums are reordered. -/
def expandedMixedZeroEntry
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a b : Fin (F.blockDim T)) : ℂ :=
  ∑ j : Fin (F.dim T),
    (∑ i : Fin (F.dim T),
      star (C.toData.compression T i a) *
        (((F.hatDenominator T)⁻¹ : ℂ) *
          ∑ ρ ∈ ZeroSide.ZI Z T,
            (Z.mult ρ : ℂ) * F.atom T i ρ *
              F.atom T j ρ)) *
      C.toData.compression T j b

/-- Opening an isometric block entry produces the explicit finite
column-column-zero sum above. -/
theorem block_apply_eq_expandedMixedZeroEntry
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a b : Fin (F.blockDim T)) :
    IsometricBlock.block C.toData T a b =
      expandedMixedZeroEntry C T a b := by
  unfold IsometricBlock.block expandedMixedZeroEntry
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply]
  simp_rw [A_apply_eq_zeroSum]


/-! ## Cyclic traces after opening the mixed block entries -/

def expandedCyclicTrace1
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) : ℝ :=
  Complex.re (∑ i : Fin (F.blockDim T),
    expandedMixedZeroEntry C T i i)

def expandedCyclicTrace2
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) : ℝ :=
  Complex.re (∑ i : Fin (F.blockDim T),
    ∑ j : Fin (F.blockDim T),
      expandedMixedZeroEntry C T i j *
        expandedMixedZeroEntry C T j i)

def expandedCyclicTrace3
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) : ℝ :=
  Complex.re (∑ i : Fin (F.blockDim T),
    ∑ j : Fin (F.blockDim T),
      (∑ k : Fin (F.blockDim T),
        expandedMixedZeroEntry C T i k *
          expandedMixedZeroEntry C T k j) *
        expandedMixedZeroEntry C T j i)

def expandedCyclicTrace4
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) : ℝ :=
  Complex.re (∑ i : Fin (F.blockDim T),
    ∑ j : Fin (F.blockDim T),
      (∑ k : Fin (F.blockDim T),
        expandedMixedZeroEntry C T i k *
          expandedMixedZeroEntry C T k j) *
      (∑ l : Fin (F.blockDim T),
        expandedMixedZeroEntry C T j l *
          expandedMixedZeroEntry C T l i))

theorem cyclicTrace1_block_eq_expanded
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    QuarticTransfer.cyclicTrace1
        (IsometricBlock.block C.toData T) =
      expandedCyclicTrace1 C T := by
  simp only [QuarticTransfer.cyclicTrace1, expandedCyclicTrace1,
    block_apply_eq_expandedMixedZeroEntry]

theorem cyclicTrace2_block_eq_expanded
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    QuarticTransfer.cyclicTrace2
        (IsometricBlock.block C.toData T) =
      expandedCyclicTrace2 C T := by
  simp only [QuarticTransfer.cyclicTrace2, expandedCyclicTrace2,
    block_apply_eq_expandedMixedZeroEntry]

theorem cyclicTrace3_block_eq_expanded
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    QuarticTransfer.cyclicTrace3
        (IsometricBlock.block C.toData T) =
      expandedCyclicTrace3 C T := by
  simp only [QuarticTransfer.cyclicTrace3, expandedCyclicTrace3,
    block_apply_eq_expandedMixedZeroEntry]

theorem cyclicTrace4_block_eq_expanded
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ) :
    QuarticTransfer.cyclicTrace4
        (IsometricBlock.block C.toData T) =
      expandedCyclicTrace4 C T := by
  simp only [QuarticTransfer.cyclicTrace4, expandedCyclicTrace4,
    block_apply_eq_expandedMixedZeroEntry]

def expandedCyclicQuarticNumerator
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : RealData F) (T : ℝ) : ℝ :=
  let u := QuarticTransfer.uncenteredQuartic q
  u.p0 * (F.blockDim T : ℝ) +
    u.p1 * expandedCyclicTrace1 C T +
    u.p2 * expandedCyclicTrace2 C T +
    u.p3 * expandedCyclicTrace3 C T +
    u.p4 * expandedCyclicTrace4 C T

theorem cyclicQuarticNumerator_block_eq_expanded
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : RealData F) (T : ℝ) :
    QuarticTransfer.cyclicQuarticTraceNumerator q
        (IsometricBlock.block C.toData T) =
      expandedCyclicQuarticNumerator q C T := by
  simp only [QuarticTransfer.cyclicQuarticTraceNumerator,
    expandedCyclicQuarticNumerator,
    cyclicTrace1_block_eq_expanded,
    cyclicTrace2_block_eq_expanded,
    cyclicTrace3_block_eq_expanded,
    cyclicTrace4_block_eq_expanded]

/-- The analytic target after mixing and pair contraction, before any
zero-tuple summation is estimated. -/
def mixedPairKernelQuarticNumerator
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (q : TrimmedMoment.Quartic)
    (C : RealData F) (T : ℝ) : ℝ :=
  QuarticTransfer.pairKernelQuarticNumerator q F T
    (mixedPairKernel C T)


/-- One zero's contribution to one entry after real column mixing. -/
def mixedBlockZeroSummand
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a b : Fin (F.blockDim T)) (ρ : ℂ) : ℂ :=
  ((F.hatDenominator T)⁻¹ : ℂ) *
    (Z.mult ρ : ℂ) *
    mixedAtom C T a ρ * mixedAtom C T b ρ

private theorem sum_fintype_finset_comm
    {ι α : Type*} [Fintype ι]
    (s : Finset α) (f : ι → α → ℂ) :
    (∑ i : ι, ∑ a ∈ s, f i a) =
      ∑ a ∈ s, ∑ i : ι, f i a := by
  rw [Finset.sum_comm]

/-- Reordering only finite sums shows that a compressed entry is again a
literal Gram sum of the mixed atoms. -/
theorem expandedMixedZeroEntry_eq_sum
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a b : Fin (F.blockDim T)) :
    expandedMixedZeroEntry C T a b =
      ∑ ρ ∈ ZeroSide.ZI Z T,
        mixedBlockZeroSummand C T a b ρ := by
  unfold expandedMixedZeroEntry
  simp_rw [C.real_entries]
  calc
    (∑ j : Fin (F.dim T),
        (∑ i : Fin (F.dim T),
          C.toData.compression T i a *
            (((F.hatDenominator T)⁻¹ : ℂ) *
              ∑ ρ ∈ ZeroSide.ZI Z T,
                (Z.mult ρ : ℂ) * F.atom T i ρ *
                  F.atom T j ρ)) *
          C.toData.compression T j b =
      ∑ j : Fin (F.dim T), ∑ i : Fin (F.dim T),
        ∑ ρ ∈ ZeroSide.ZI Z T,
          ((F.hatDenominator T)⁻¹ : ℂ) *
            (Z.mult ρ : ℂ) *
            C.toData.compression T i a *
            C.toData.compression T j b *
            F.atom T i ρ * F.atom T j ρ := by
      apply Finset.sum_congr rfl
      intro j _
      rw [Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro i _
      simp only [Finset.mul_sum, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro ρ _
      ring
    _ = ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
        ∑ ρ ∈ ZeroSide.ZI Z T,
          ((F.hatDenominator T)⁻¹ : ℂ) *
            (Z.mult ρ : ℂ) *
            C.toData.compression T i a *
            C.toData.compression T j b *
            F.atom T i ρ * F.atom T j ρ := by
      rw [Finset.sum_comm]
    _ = ∑ i : Fin (F.dim T),
        ∑ ρ ∈ ZeroSide.ZI Z T, ∑ j : Fin (F.dim T),
          ((F.hatDenominator T)⁻¹ : ℂ) *
            (Z.mult ρ : ℂ) *
            C.toData.compression T i a *
            C.toData.compression T j b *
            F.atom T i ρ * F.atom T j ρ := by
      apply Finset.sum_congr rfl
      intro i _
      rw [sum_fintype_finset_comm]
    _ = ∑ ρ ∈ ZeroSide.ZI Z T,
        ∑ i : Fin (F.dim T), ∑ j : Fin (F.dim T),
          ((F.hatDenominator T)⁻¹ : ℂ) *
            (Z.mult ρ : ℂ) *
            C.toData.compression T i a *
            C.toData.compression T j b *
            F.atom T i ρ * F.atom T j ρ := by
      rw [sum_fintype_finset_comm]
    _ = ∑ ρ ∈ ZeroSide.ZI Z T,
        mixedBlockZeroSummand C T a b ρ := by
      apply Finset.sum_congr rfl
      intro ρ _
      unfold mixedBlockZeroSummand mixedAtom
      simp only [Finset.mul_sum, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro i _
      apply Finset.sum_congr rfl
      intro j _
      ring

/-- The actual isometric block entry is the finite zero Gram sum of the
mixed atoms. -/
theorem block_apply_eq_mixedZeroSum
    {Z : ZeroConfig} {σ μ p : ℝ} {v : ℝ → ℝ}
    {F : QuarticGramFamily Z σ μ p v}
    (C : RealData F) (T : ℝ)
    (a b : Fin (F.blockDim T)) :
    IsometricBlock.block C.toData T a b =
      ∑ ρ ∈ ZeroSide.ZI Z T,
        mixedBlockZeroSummand C T a b ρ := by
  rw [block_apply_eq_expandedMixedZeroEntry,
    expandedMixedZeroEntry_eq_sum]

end IsometricKernel
end Zeta85
end RH

end
